### ISSUE TITLE
Add comment templates

### ISSUE THREAD

**Issue by j-f1** [liuderchi/gh-template-bot#6]
I help triage issues on a repository, and it would be really useful if I could just put `/reply duplicate 1234` or `/reply repro-steps` in a comment and have my comment edited into a helpful response for the OP.

**Comment by liuderchi** [comment]
@j-f1 that's really awesome idea. It really extends a bot's ability of making templates.
Like #5, the most complex part of such feature is design of *interpolation* of values into a template.

By the time bot can access custom templates from `.github`, I would implement this feature.

---

IMO I would like to keep bot command usage simple, so I would prefer 
  - always use `/template` as a directive
  - maybe we command would be `/template reply_duplicate 1234` then the bot
      - grab `.github/REPLY_DUPLICATE.md` and insert 1234 into `$1` part of the template

**Comment by liuderchi** [comment]
@j-f1 this feature is added in latest release v0.2.0 🎉 
You may install it to your repo or try it in #10 playground.
